#coding=utf-8

##==================================请求头参数（开发测试生产环境通用）=======================
#请求头参数-前端系统版本号
SYSVERSION:'11.2.1'

#请求头参数-设备号
deviceToken:'cb9012fd0302813461884e4a3fcc382886b73f6518c1dbe1f031a3901ee72eb4'

#请求头参数-客户端浏览器
UserAgent:'joyRunner/3.1.0 (iPhone; iOS 11.2.1; Scale/3.00)'

#请求头参数-APP的开发版本号
APPDEVINFO:'iOS#3.1.0.01101444'

#请求头参数-设备类型
MODELTYPE:'iPhone 7 Plus'

#请求头参数-cookies中app的版本号信息
appversion:'ios3.1.1'

#请求头参数Content-Type
#ContentType:'application/x-www-form-urlencoded'

# # 环境变量（Test,Online）

#=======================线上发布连接地址(Online)========================
# 登录地址
login_URL:'http://api.thejoyrun.com' 

#api项目地址
api_URL:'http://api.thejoyrun.com' 

#beta约定跑相关
beta_URL:'http://beta.thejoyrun.com'

#bet 动态配置相关
bet_URL:'http://bet.api.thejoyrun.com'

# user用户工程,与用户信息相关
user_URL:'http://u.api.thejoyrun.com' 

# topic工程,与首页相关
topic_URL:'http://topic.api.thejoyrun.com' 

#crew-muilt 与跑团相关1
crew_muilt_URL:'http://crew-muilt.api.thejoyrun.com' 

#crew 与跑团相关2
crew_URL:'http://crew.api.thejoyrun.com' 

#crewapp 跑团相关3
crewapp_URL:'http://crewapp.api.thejoyrun.com'

# ec电商工程,与订单相关
ec_URL:'http://ec.thejoyrun.com'

# advert工程,与消息广告通告相关
advert_URL:'http://advert.api.thejoyrun.com'

# training工程,与训练相关
training_URL:'http://training.api.thejoyrun.com'

# wear工程,与穿戴相关
wear_URL:'http://wear.api.thejoyrun.com'

#point_
point_URL:'http://point.api.thejoyrun.com'

#im 消息相关
im_URL:'http://im.api.thejoyrun.com'

#marathon 马拉松相关
marathon_URL:'http://marathon.api.thejoyrun.com'

#recommend 推荐相关
recommend_URL:'http://recommend.api.thejoyrun.com'

#live 赛事直播相关
live_URL:'http://live.api.thejoyrun.com'

#wallet 推荐相关
wallet_URL:'http://wallet.api.thejoyrun.com'

#media 媒体资讯相关
media_URL:'http://media.api.thejoyrun.com'

#challenge 挑战相关
challenge_URL:'http://challenge.api.thejoyrun.com'

#event 事件相关
event_URL:'http://event.api.thejoyrun.com'

#跑团小程序
mapp_URL:'https://mapp.api.thejoyrun.com'

企业跑团
cr_URL:'https://cr.thejoyrun.com'

#各版本测试（3.1）密钥
appkey1:'fb1931e425f84313bfae4b93ab3ccdc4'

#业务测试密钥
appkey2:'1fd6e28fd158406995f77727b35bf20a'

#前端验签名的版本号（需要与appkey1相对应，服务根据这个版本号验证appkey1）
APPVERSION:'100.3.1.0'

#跑团小程序密钥
crewappkey:'0a7d4aa5-c13c-40c2-9b1e-3476071a6f82'

#跑团小程序APPID
appid:'wx24fffb22401a1157'

#跑团小程序用户身份sid===2018-02-06  10:28
sid:'6861e3f7620840c2b03d8eff181a61d70'

#线上运行用户列表   注意以下用名的密码要一致；
Onlineuserlist:'13829744541,13926281760,5145311'

#测试运行用户列表   注意以下用名的密码要一致；
Testuserlist:'13829744541,13829744542,13829744543,13829744544,13829744545,5145311'


# # pybot --include Online  --variable login_URL:http://api.thejoyrun.com --variable api_URL:http://api.thejoyrun.com --variable beta_URL:http://beta.thejoyrun.com --variable bet_URL:http://bet.api.thejoyrun.com --variable user_URL:http://u.api.thejoyrun.com --variable topic_URL:http://topic.api.thejoyrun.com --variable crew_muilt_URL:http://crew-muilt.api.thejoyrun.com --variable crew_URL:http://crew.api.thejoyrun.com --variable crewapp_URL:http://crewapp.api.thejoyrun.com --variable ec_URL:http://ec.thejoyrun.com   --variable advert_URL:http://advert.api.thejoyrun.com  --variable training_URL:http://training.api.thejoyrun.com  --variable wear_URL:http://wear.api.thejoyrun.com  --variable   point_URL:http://point.api.thejoyrun.com --variable im_URL:http://im.api.thejoyrun.com  --variable marathon_URL:http://marathon.api.thejoyrun.com  --variable recommend_URL:http://recommend.api.thejoyrun.com  --variable live_URL:http://live.api.thejoyrun.com  --variable wallet_URL:http://wallet.api.thejoyrun.com --variable media_URL:http://media.api.thejoyrun.com  --variable challenge_URL:http://challenge.api.thejoyrun.com  --variable event_URL:http://event.api.thejoyrun.com  --variable mapp_URL:https://mapp.api.thejoyrun.com --variable appkey1:fb1931e425f84313bfae4b93ab3ccdc4  --variable appkey2:1fd6e28fd158406995f77727b35bf20a  --variable APPVERSION:100.3.1.0 --variable corpcrewappkey:0a7d4aa5-c13c-40c2-9b1e-3476071a6f82  --variable corpcrewappid:wx24fffb22401a1157 --variable corpcrewsid:6861e3f7620840c2b03d8eff181a61d70 -d /var/lib/jenkins/Report/${BUILD_TIMESTAMP}  ${JENKINS_HOME}/workspace/JoyrunServer/Online_Master_30_Min